const SITE_VERSION = "v1.0.0";

const headers = {
  "content-type": "text/html; charset=UTF-8",
  "cache-control": "public, max-age=300, s-maxage=3600",
  "x-content-type-options": "nosniff",
  "referrer-policy": "strict-origin-when-cross-origin",
  "permissions-policy": "camera=(), microphone=(), geolocation=(), payment=(), usb=()",
  "content-security-policy": "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'none'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'; upgrade-insecure-requests",
  "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
};

const html = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover" />
<meta name="theme-color" content="#070708" />
<meta name="color-scheme" content="dark" />
<meta name="description" content="DPRGRMMD — systems, interfaces and infrastructure engineered as one continuous experience." />
<meta property="og:title" content="DPRGRMMD" />
<meta property="og:description" content="The system behind the experience." />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://dprgrmmd.com/" />
<meta name="twitter:card" content="summary_large_image" />
<link rel="canonical" href="https://dprgrmmd.com/" />
<title>DPRGRMMD — The system behind the experience.</title>
<style>
:root{--bg:#070708;--fg:#f1f0ec;--muted:#9e9d98;--hair:rgba(255,255,255,.14);--panel:rgba(255,255,255,.035);--accent:#d5e8ff;--mx:50%;--my:50%}
*{box-sizing:border-box}html{scroll-behavior:smooth;background:var(--bg)}body{margin:0;background:var(--bg);color:var(--fg);font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;overflow-x:hidden;cursor:none}a{color:inherit;text-decoration:none}button,a{cursor:none}::selection{background:#e7edf7;color:#08090a}
.noise{position:fixed;inset:0;pointer-events:none;z-index:80;opacity:.055;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.9'/%3E%3C/svg%3E")}
.cursor{position:fixed;top:0;left:0;width:16px;height:16px;border:1px solid rgba(255,255,255,.68);border-radius:50%;pointer-events:none;z-index:100;transform:translate(-50%,-50%);transition:width .2s,height .2s,background .2s,border-color .2s;mix-blend-mode:difference}.cursor.hot{width:54px;height:54px;background:#fff;border-color:#fff}
.topbar{position:fixed;top:0;left:0;right:0;z-index:30;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:22px 28px;font-size:10px;letter-spacing:.22em;text-transform:uppercase;color:rgba(255,255,255,.8);mix-blend-mode:difference}.brand{font-weight:650}.topbar .center{opacity:.6}.topbar .right{text-align:right}.dot{display:inline-block;width:5px;height:5px;border-radius:50%;background:#bbffc8;box-shadow:0 0 12px rgba(187,255,200,.65);margin-right:8px;vertical-align:1px}
.hero{position:relative;min-height:100svh;display:flex;align-items:flex-end;overflow:hidden;border-bottom:1px solid var(--hair)}#field{position:absolute;inset:0;width:100%;height:100%;display:block;opacity:.92}.hero:after{content:"";position:absolute;inset:0;background:radial-gradient(circle at var(--mx) var(--my),rgba(255,255,255,.05),transparent 24%),linear-gradient(to top,rgba(7,7,8,.96) 0%,rgba(7,7,8,.18) 52%,rgba(7,7,8,.58) 100%);pointer-events:none}
.hero-copy{position:relative;z-index:2;width:100%;padding:0 28px 24px}.kicker{display:flex;justify-content:space-between;align-items:flex-end;border-top:1px solid var(--hair);padding-top:13px;margin-bottom:14px;font:500 10px/1.25 ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.17em;color:rgba(255,255,255,.58)}.hero-title{font-size:clamp(58px,14.2vw,224px);line-height:.75;letter-spacing:-.072em;font-weight:650;margin:0 0 26px;text-transform:uppercase;white-space:nowrap;transform:translateX(-.012em)}.hero-bottom{display:grid;grid-template-columns:1.2fr .8fr;gap:30px;align-items:end}.hero-statement{max-width:620px;font-size:clamp(19px,2.3vw,34px);line-height:1.05;letter-spacing:-.035em}.scroll{justify-self:end;font:500 10px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.16em;text-transform:uppercase;color:var(--muted)}
.section{position:relative;padding:140px 28px;border-bottom:1px solid var(--hair)}.eyebrow{display:grid;grid-template-columns:1fr 1fr;margin-bottom:90px;font:500 10px/1.35 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.15em;text-transform:uppercase;color:var(--muted)}.eyebrow span:last-child{text-align:right}.statement{max-width:1400px;margin:0;font-size:clamp(48px,8.3vw,128px);line-height:.89;letter-spacing:-.062em;font-weight:560}.statement .dim{color:#4b4b4d}.statement .glint{background:linear-gradient(95deg,#fff 0%,#aab7c8 44%,#fff 61%,#787f88 100%);-webkit-background-clip:text;background-clip:text;color:transparent}
.matrix{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--hair);border-left:1px solid var(--hair)}.cell{min-height:420px;padding:25px;display:flex;flex-direction:column;justify-content:space-between;border-right:1px solid var(--hair);border-bottom:1px solid var(--hair);position:relative;overflow:hidden;background:var(--panel);transition:background .35s,transform .35s}.cell:before{content:"";position:absolute;width:280px;height:280px;border-radius:50%;left:var(--x,50%);top:var(--y,50%);transform:translate(-50%,-50%);background:radial-gradient(circle,rgba(204,224,255,.14),transparent 68%);opacity:0;transition:opacity .25s}.cell:hover{background:rgba(255,255,255,.055)}.cell:hover:before{opacity:1}.cell-index{font:500 10px/1 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted);letter-spacing:.1em}.cell h3{margin:0;font-size:clamp(36px,4vw,64px);letter-spacing:-.055em;line-height:.9;font-weight:520}.cell p{max-width:34ch;margin:18px 0 0;color:var(--muted);font-size:13px;line-height:1.5}.cell .arrow{position:absolute;right:22px;top:20px;font-size:20px;color:rgba(255,255,255,.38);transform:rotate(-45deg)}
.marquee{overflow:hidden;padding:17px 0;border-bottom:1px solid var(--hair);white-space:nowrap}.marquee-track{display:inline-flex;gap:24px;animation:marquee 24s linear infinite;font-size:13px;letter-spacing:.16em;text-transform:uppercase;color:rgba(255,255,255,.62)}.marquee-track b{font-weight:400;color:#fff}@keyframes marquee{to{transform:translateX(-50%)}}
.manifesto{min-height:100svh;display:grid;grid-template-columns:.42fr 1.58fr;gap:60px;align-items:start}.manifesto .label{position:sticky;top:120px;font:500 10px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.16em;color:var(--muted)}.manifesto-copy{font-size:clamp(34px,5.5vw,78px);line-height:.98;letter-spacing:-.048em}.manifesto-copy p{margin:0 0 1em}.manifesto-copy .small{font-size:clamp(18px,2vw,28px);line-height:1.2;letter-spacing:-.025em;color:var(--muted);max-width:650px;margin-left:auto}
.footer{min-height:88svh;display:flex;flex-direction:column;justify-content:space-between;padding:32px 28px 24px;position:relative;overflow:hidden}.footer:before{content:"";position:absolute;width:min(72vw,980px);aspect-ratio:1;border:1px solid rgba(255,255,255,.13);border-radius:50%;left:50%;top:44%;transform:translate(-50%,-50%);box-shadow:0 0 120px rgba(160,190,230,.05),inset 0 0 120px rgba(160,190,230,.03)}.footer-top{display:flex;justify-content:space-between;font:500 10px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.14em;color:var(--muted)}.footer-word{position:relative;z-index:2;margin:auto 0 0;font-size:clamp(62px,15vw,236px);line-height:.71;letter-spacing:-.075em;font-weight:650}.footer-bottom{position:relative;z-index:2;display:flex;justify-content:space-between;align-items:end;border-top:1px solid var(--hair);padding-top:14px;font-size:11px;color:var(--muted)}.footer-bottom strong{color:var(--fg);font-weight:500}.reveal{opacity:0;transform:translateY(28px);transition:opacity .8s cubic-bezier(.2,.75,.2,1),transform .8s cubic-bezier(.2,.75,.2,1)}.reveal.in{opacity:1;transform:none}
@media(max-width:900px){body{cursor:auto}.cursor{display:none}.topbar{padding:18px 17px;grid-template-columns:1fr auto}.topbar .center{display:none}.hero-copy{padding:0 17px 18px}.hero-title{font-size:21.5vw;letter-spacing:-.075em}.hero-bottom{grid-template-columns:1fr}.scroll{justify-self:start}.section{padding:96px 17px}.eyebrow{margin-bottom:60px}.matrix{grid-template-columns:1fr}.cell{min-height:320px}.manifesto{grid-template-columns:1fr}.manifesto .label{position:static}.footer{padding:24px 17px 18px}.footer-bottom{gap:20px;flex-direction:column;align-items:flex-start}.kicker span:last-child{display:none}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.marquee-track{animation:none}.reveal{opacity:1;transform:none;transition:none}#field{opacity:.65}}
</style>
</head>
<body>
<div class="noise" aria-hidden="true"></div><div class="cursor" aria-hidden="true"></div>
<nav class="topbar" aria-label="Primary"><div class="brand">DPRGRMMD</div><div class="center">Digital systems / 2026</div><div class="right"><span class="dot"></span>Online</div></nav>
<main>
<section class="hero" id="top"><canvas id="field" aria-hidden="true"></canvas><div class="hero-copy"><div class="kicker"><span>Independent technology practice</span><span>43.6532° N / 79.3832° W</span></div><h1 class="hero-title">DPRGRMMD</h1><div class="hero-bottom"><div class="hero-statement">The system behind the experience. <span style="color:var(--muted)">Designed without seams.</span></div><div class="scroll">Scroll to enter &nbsp; ↓</div></div></div></section>
<div class="marquee" aria-hidden="true"><div class="marquee-track"><span>Systems</span><span>×</span><b>Interfaces</b><span>×</span><span>Infrastructure</span><span>×</span><b>Automation</b><span>×</span><span>Media</span><span>×</span><b>Security</b><span>×</span><span>Systems</span><span>×</span><b>Interfaces</b><span>×</span><span>Infrastructure</span><span>×</span><b>Automation</b><span>×</span><span>Media</span><span>×</span><b>Security</b><span>×</span></div></div>
<section class="section"><div class="eyebrow reveal"><span>01 / Intent</span><span>One continuous system</span></div><h2 class="statement reveal">We design <span class="dim">beyond the screen.</span> <span class="glint">Every layer</span> is part of the experience.</h2></section>
<section class="section"><div class="eyebrow reveal"><span>02 / Practice</span><span>Selected disciplines</span></div><div class="matrix">
<article class="cell reveal"><span class="cell-index">A.01</span><span class="arrow">→</span><div><h3>Systems</h3><p>Architecture that turns complexity into a controlled, legible environment.</p></div></article>
<article class="cell reveal"><span class="cell-index">A.02</span><span class="arrow">→</span><div><h3>Interfaces</h3><p>High-clarity interaction systems where visual language and operational logic become one.</p></div></article>
<article class="cell reveal"><span class="cell-index">A.03</span><span class="arrow">→</span><div><h3>Infrastructure</h3><p>Edge-first foundations engineered for resilience, observability, speed and change.</p></div></article>
<article class="cell reveal"><span class="cell-index">B.01</span><span class="arrow">→</span><div><h3>Automation</h3><p>Intent translated into repeatable systems that remove friction without removing control.</p></div></article>
<article class="cell reveal"><span class="cell-index">B.02</span><span class="arrow">→</span><div><h3>Media</h3><p>Broadcast, routing and spatial experiences built as programmable technical surfaces.</p></div></article>
<article class="cell reveal"><span class="cell-index">B.03</span><span class="arrow">→</span><div><h3>Security</h3><p>Security as architecture: embedded, measurable and invisible until it needs to be seen.</p></div></article>
</div></section>
<section class="section manifesto"><div class="label reveal">03 / Position<br><br>DPRGRMMD does not separate<br>design from engineering.</div><div class="manifesto-copy"><p class="reveal">The future is not a visual effect.</p><p class="reveal" style="color:#7f8084">It is what happens when technology becomes calm enough to disappear.</p><p class="small reveal">We build across disciplines because the seams between disciplines are usually where the experience breaks. The interface, network, automation, media layer and security model should feel like decisions made by the same intelligence.</p></div></section>
</main>
<footer class="footer"><div class="footer-top"><span>04 / End transmission</span><span>DPRGRMMD.COM</span></div><div class="footer-word">MAKE<br>IT REAL.</div><div class="footer-bottom"><div><strong>DPRGRMMD</strong><br>The system behind the experience.</div><div>Built at the edge<br>Cloudflare / ${SITE_VERSION}</div><a href="#top" class="hotlink">Back to top ↗</a></div></footer>
<script>
(()=>{const root=document.documentElement,cursor=document.querySelector('.cursor');let cx=innerWidth/2,cy=innerHeight/2,tx=cx,ty=cy;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY;root.style.setProperty('--mx',e.clientX/innerWidth*100+'%');root.style.setProperty('--my',e.clientY/innerHeight*100+'%')},{passive:true});function c(){cx+=(tx-cx)*.18;cy+=(ty-cy)*.18;cursor.style.transform='translate('+cx+'px,'+cy+'px) translate(-50%,-50%)';requestAnimationFrame(c)}c();document.querySelectorAll('a,.cell').forEach(el=>{el.addEventListener('pointerenter',()=>cursor.classList.add('hot'));el.addEventListener('pointerleave',()=>cursor.classList.remove('hot'))});document.querySelectorAll('.cell').forEach(el=>el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.setProperty('--x',e.clientX-r.left+'px');el.style.setProperty('--y',e.clientY-r.top+'px')}));const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
const canvas=document.getElementById('field'),gl=canvas.getContext('webgl',{antialias:false,alpha:false,powerPreference:'high-performance'});if(!gl){canvas.style.background='radial-gradient(circle at 62% 35%,#29313c 0,#111318 34%,#070708 72%)';return}const vs='attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}';const fs='precision highp float;uniform vec2 r;uniform vec2 m;uniform float t;float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1,0)),f.x),mix(h(i+vec2(0,1)),h(i+vec2(1)),f.x),f.y);}float fb(vec2 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*n(p);p=p*2.03+17.17;a*=.5;}return v;}void main(){vec2 uv=(gl_FragCoord.xy-.5*r)/min(r.x,r.y);vec2 mm=(m-.5)*vec2(r.x/r.y,1.);float tt=t*.055;float q=fb(uv*1.75+vec2(tt,-tt*.6));float z=fb(uv*3.1+q*1.7+vec2(-tt*.8,tt));float d=length(uv-mm*.45);float orb=exp(-d*2.8);float edge=smoothstep(.15,.92,z+orb*.42);vec3 a=vec3(.018,.02,.025),b=vec3(.18,.23,.31),c=vec3(.78,.84,.93);vec3 col=mix(a,b,edge*.72);col=mix(col,c,pow(max(0.,z-.59),3.)*2.4+orb*.05);float vign=smoothstep(1.35,.24,length(uv));col*=.72+.28*vign;gl_FragColor=vec4(col,1.);}';function sh(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);return s}const pr=gl.createProgram();gl.attachShader(pr,sh(gl.VERTEX_SHADER,vs));gl.attachShader(pr,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(pr);gl.useProgram(pr);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const p=gl.getAttribLocation(pr,'p');gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,2,gl.FLOAT,false,0,0);const ur=gl.getUniformLocation(pr,'r'),um=gl.getUniformLocation(pr,'m'),ut=gl.getUniformLocation(pr,'t');let mx=.5,my=.5;addEventListener('pointermove',e=>{mx=e.clientX/innerWidth;my=1-e.clientY/innerHeight},{passive:true});function resize(){const d=Math.min(devicePixelRatio,1.6),w=Math.floor(canvas.clientWidth*d),h=Math.floor(canvas.clientHeight*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}}let start=performance.now(),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;function draw(now){resize();gl.uniform2f(ur,canvas.width,canvas.height);gl.uniform2f(um,mx-.5,my-.5);gl.uniform1f(ut,reduce?0:(now-start)/1000);gl.drawArrays(gl.TRIANGLES,0,3);if(!reduce)requestAnimationFrame(draw)}requestAnimationFrame(draw)})();
</script>
</body></html>`;

async function handleRequest(request) {
  const url = new URL(request.url);
  if (request.method !== "GET" && request.method !== "HEAD") {
    return new Response("Method Not Allowed", { status: 405, headers: { allow: "GET, HEAD" } });
  }
  if (url.pathname === "/health") {
    return Response.json({ ok: true, service: "dprgrmmd-site", version: SITE_VERSION }, { headers: { "cache-control": "no-store" } });
  }
  if (url.pathname === "/robots.txt") {
    return new Response("User-agent: *\nAllow: /\nSitemap: https://dprgrmmd.com/sitemap.xml\n", { headers: { "content-type": "text/plain; charset=UTF-8", "cache-control": "public, max-age=86400" } });
  }
  if (url.pathname === "/sitemap.xml") {
    return new Response('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://dprgrmmd.com/</loc><changefreq>weekly</changefreq><priority>1.0</priority></url></urlset>', { headers: { "content-type": "application/xml; charset=UTF-8", "cache-control": "public, max-age=86400" } });
  }
  if (url.pathname !== "/" && url.pathname !== "/index.html") {
    return new Response("Not Found", { status: 404, headers: { "content-type": "text/plain; charset=UTF-8" } });
  }
  return new Response(request.method === "HEAD" ? null : html, { headers });
}

addEventListener("fetch", event => {
  event.respondWith(handleRequest(event.request));
});
